version: "3.8"
services:
# PHP
  php:
    image: php:8.1-apache
    container_name: phpVeliko
    ports:
      - "8085:80"
    volumes:
      - ./public:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
  # PHP My Admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_Veliko
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      #PMA_PASSWORD: groupe6
  # Base de donn√©es MySQL
  db:
    image: mysql:8.0
    #mage: mariadb:10.3
    container_name: mysql_Veliko
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql/init_test.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: groupe6
      MYSQL_DATABASE: bdd_veliko




